name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build Release APK
        run: |
          ./gradlew --no-daemon assembleRelease

      - name: Rename APK
        run: |
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/Dhizuku-${{ github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/Dhizuku-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
